# Applies (or removes) the XOR mask on the fx_* PROGMEM tables in effect_data.h.
#
# Why: on this Mega the USB-serial upload path corrupts the unmasked effect-data
# byte patterns and avrdude dies partway through the flash write ("timeout" /
# "failed to execute command 0x13"). The very same pages upload fine once the
# bytes are XOR-masked. d_light_effects.ino undoes the mask on every read in
# fx_read(), so the colours on the playfield are unchanged.
#
# effect_data.h is GENERATED by the CnC Light Editor -- run this after every
# regeneration. Forgetting is not silent: the FX_DATA_MASK_APPLIED define this
# script inserts is checked by an #error in d_light_effects.ino, so an unmasked
# effect_data.h fails to compile instead of producing wrong colours.
#
#   .\mask_effect_data.ps1            # mask (refuses if already masked)
#   .\mask_effect_data.ps1 -Unmask    # back to plain data
#
# If a future effect set still fails to upload, change MASK here and
# FX_DATA_MASK in d_light_effects.ino to the same new value and re-run.

param(
  [string]$Path = "$PSScriptRoot\effect_data.h",
  [switch]$Unmask
)

[int]$MASK   = 0x5A
$markerRx    = '^\s*#define\s+FX_DATA_MASK_APPLIED\b'

if (-not (Test-Path $Path)) { Write-Error "not found: $Path"; exit 1 }

$lines    = [System.IO.File]::ReadAllLines($Path)
$markerAt = -1
for ($i = 0; $i -lt $lines.Count; $i++) { if ($lines[$i] -match $markerRx) { $markerAt = $i; break } }
$isMasked = ($markerAt -ge 0)

if ($Unmask -and -not $isMasked) { Write-Error "already unmasked: $Path"; exit 1 }
if (-not $Unmask -and $isMasked) { Write-Error "already masked: $Path (use -Unmask first)"; exit 1 }

# On unmask, drop the marker block: the #define plus the comment lines hugging
# it, plus the blank line that separates it from the includes above.
if ($Unmask) {
  $start = $markerAt
  while ($start -gt 0 -and $lines[$start - 1].TrimStart().StartsWith('//')) { $start-- }
  if ($start -gt 0 -and $lines[$start - 1].Trim() -eq '') { $start-- }
  $end = $markerAt
  while ($end -lt $lines.Count - 1 -and $lines[$end + 1].TrimStart().StartsWith('//')) { $end++ }
  $kept = New-Object System.Collections.Generic.List[string]
  for ($i = 0; $i -lt $lines.Count; $i++) { if ($i -lt $start -or $i -gt $end) { $kept.Add($lines[$i]) } }
  $lines = $kept.ToArray()
}

$out     = New-Object System.Collections.Generic.List[string]
$inArr   = $false
$arrays  = 0
$changed = 0
$ev = [System.Text.RegularExpressions.MatchEvaluator]{
  param($m)
  $script:changed++
  return [string]([int]$m.Value -bxor $script:MASK)
}

foreach ($line in $lines) {
  if (-not $inArr) {
    $out.Add($line)
    if ($line -match '^\s*const\s+uint8_t\s+fx_\w+\[\]\s+PROGMEM\s*=\s*\{') { $inArr = $true; $arrays++ }
    continue
  }
  if ($line -match '^\s*\};')             { $inArr = $false; $out.Add($line); continue }
  if ($line.TrimStart().StartsWith('//')) { $out.Add($line); continue }
  $out.Add([regex]::Replace($line, '\d+', $ev))
}

# On mask, insert the marker block right after the pgmspace include.
if (-not $Unmask) {
  $final = New-Object System.Collections.Generic.List[string]
  $done  = $false
  foreach ($line in $out) {
    $final.Add($line)
    if (-not $done -and $line -match '^\s*#include\s+<avr/pgmspace\.h>') {
      $final.Add("")
      $final.Add("// Must match FX_DATA_MASK in d_light_effects.ino; that file #errors if it doesn't.")
      $final.Add(("#define FX_DATA_MASK_APPLIED 0x{0:X2}" -f $MASK))
      $final.Add("// The fx_* tables below are stored XOR-masked; d_light_effects.ino undoes it in")
      $final.Add("// fx_read(). Without the mask this board's USB-serial upload dies at 28% of the")
      $final.Add("// flash write. If you regenerate this file with the CnC Light Editor, re-run")
      $final.Add("// mask_effect_data.ps1 or the build will stop with an #error.")
      $done = $true
    }
  }
  if (-not $done) { Write-Error "no '#include <avr/pgmspace.h>' line to anchor the marker to"; exit 1 }
  $out = $final
}

[System.IO.File]::WriteAllLines($Path, $out)
"{0}: {1} arrays, {2} values" -f $(if ($Unmask) { "unmasked" } else { "masked" }), $arrays, $changed
