# Applies (or removes) the XOR mask on the fx_* PROGMEM tables in effect_data.h.
#
# Why: on this Mega the USB-serial upload path corrupts the unmasked effect-data
# byte patterns and avrdude dies partway through the flash write ("timeout" /
# "failed to execute command 0x13"). The very same pages upload fine once the
# bytes are XOR-masked. d_light_effects.ino undoes the mask on every read in
# fx_read(), so the colours on the playfield are unchanged.
#
# effect_data.h is GENERATED by the CnC Light Editor -- run this after every
# regeneration, otherwise the effects come out with wrong colours.
#
#   .\mask_effect_data.ps1            # mask (refuses if already masked)
#   .\mask_effect_data.ps1 -Unmask    # back to plain data
#
# Keep MASK in sync with FX_DATA_MASK in d_light_effects.ino.

param(
  [string]$Path = "$PSScriptRoot\effect_data.h",
  [switch]$Unmask
)

[int]$MASK = 0x5A
$marker = "// FX_DATA_XOR_MASKED: 0x{0:X2}" -f $MASK

if (-not (Test-Path $Path)) { Write-Error "not found: $Path"; exit 1 }

$lines    = [System.IO.File]::ReadAllLines($Path)
$isMasked = ($lines | Where-Object { $_.StartsWith($marker) }).Count -gt 0

if ($Unmask -and -not $isMasked) { Write-Error "already unmasked: $Path"; exit 1 }
if (-not $Unmask -and $isMasked) { Write-Error "already masked: $Path (use -Unmask first)"; exit 1 }

$out     = New-Object System.Collections.Generic.List[string]
$inArr   = $false
$arrays  = 0
$changed = 0
$ev = [System.Text.RegularExpressions.MatchEvaluator]{
  param($m)
  $script:changed++
  return [string]([int]$m.Value -bxor $script:MASK)
}

foreach ($line in $lines) {
  # Drop the marker block when unmasking.
  if ($Unmask -and $line.StartsWith($marker)) { $script:skipBlock = $true; continue }
  if ($Unmask -and $script:skipBlock) {
    if ($line.TrimStart().StartsWith('//')) { continue }
    $script:skipBlock = $false
    if ($line.Trim() -eq '') { continue }
  }

  if (-not $inArr) {
    $out.Add($line)
    if ($line -match '^\s*const\s+uint8_t\s+fx_\w+\[\]\s+PROGMEM\s*=\s*\{') { $inArr = $true; $arrays++ }
    continue
  }
  if ($line -match '^\s*\};')                { $inArr = $false; $out.Add($line); continue }
  if ($line.TrimStart().StartsWith('//'))    { $out.Add($line); continue }
  $out.Add([regex]::Replace($line, '\d+', $ev))
}

if (-not $Unmask) {
  # Insert the marker block right after the pgmspace include.
  $final = New-Object System.Collections.Generic.List[string]
  $done  = $false
  foreach ($line in $out) {
    $final.Add($line)
    if (-not $done -and $line -match '^\s*#include\s+<avr/pgmspace\.h>') {
      $final.Add("")
      $final.Add($marker)
      $final.Add("// The fx_* tables below are stored XOR-masked; d_light_effects.ino undoes it in")
      $final.Add("// fx_read(). Without the mask this board's USB-serial upload dies at 28% of the")
      $final.Add("// flash write. If you regenerate this file with the CnC Light Editor, re-run")
      $final.Add("// mask_effect_data.ps1 or the effects will come out with wrong colours.")
      $done = $true
    }
  }
  $out = $final
}

[System.IO.File]::WriteAllLines($Path, $out)
"{0}: {1} arrays, {2} values" -f $(if ($Unmask) { "unmasked" } else { "masked" }), $arrays, $changed
